; platformio.ini
[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    ; EEPROM.h
    ; SoftwareSerial.h
lib_extra_dirs = src/libs
;build_flags = 
    ;-std=gnu++17          ; C++17 для классов

[env:nano328new]
platform = atmelavr
board = nanoatmega328new

[env:nano328]
platform = atmelavr
board = nanoatmega328
