importScripts('js/sw-toolbox.js');

toolbox.precache([
  '/styles/buttons.css',
  '/styles/forms.css',
  '/styles/inputs.css',
  '/styles/styles.css',
  '/styles/terminal.css',
  '/js/companion.js',
  '/js/forms.js',
  '/js/settings.js',
  '/js/terminal.js',
  '/js/sw-toolbox.js',
  '/js/main.js',
  '/images/blue.jpg',
  '/images/green.jpg',
  '/images/yellow.jpg',
  '/images/red.jpg',
  '/images/modalCross.svg',
  '/sounds/click.mp3',
  '/sounds/creak.mp3',
  '/index.html',
]);
